parameters:
#    spartak_projet.example.class: Spartak\ProjetBundle\Example

services:
#    spartak_projet.example:
#        class: %spartak_projet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
