parameters:
#    spartak_user.example.class: spartak\UserBundle\Example

services:
#    spartak_user.example:
#        class: %spartak_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
